name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Of een andere branch waar je de deployment van wilt triggeren

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Pas dit aan afhankelijk van je testcommand

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          sam deploy \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --stack-name my-sam-app \
            --region $AWS_DEFAULT_REGION
